name = "AcceleratedTrafficAssignement"
uuid = "01491a18-7338-4144-984c-5e8a3c91a672"
version = "1.0.0-DEV"
authors = ["AntoineBut <antoine.buttier@epfl.ch> and contributors"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FasterShortestPaths = "952f73ac-809b-4467-8cda-03990de1fa90"
GPUGraphs = "fd5a6e86-c761-4989-bab7-5b3464417f6b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[sources]
GPUGraphs = {url = "https://github.com/AntoineBut/GPUGraphs.jl"}
FasterShortestPaths = {url = "https://github.com/gdalle/FasterShortestPaths.jl"}

[compat]
DataStructures = "0.19.1"
FasterShortestPaths = "0.1.0"
GPUGraphs = "1.0.0"
Graphs = "1.13.1"
KernelAbstractions = "0.9.39"
SimpleWeightedGraphs = "1.5.0"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
